# Generated by Django 4.2.27 on 2025-12-21 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("chat_id", models.CharField(db_index=True, max_length=128)),
                ("title", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("poll_options", models.JSONField(default=list)),
                ("options_obj", models.JSONField(blank=True, default=dict)),
                ("type", models.CharField(default="native", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_id", models.CharField(max_length=255)),
                ("selected_options", models.JSONField(default=list)),
                ("selected_indexes", models.JSONField(default=list)),
                ("selected_names", models.JSONField(default=list)),
                ("ts", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="polls.poll",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["voter_id"], name="polls_vote_voter_i_2e1da8_idx"
                    )
                ],
            },
        ),
    ]
