# Generated by Django 4.2.27 on 2025-12-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_add_spotify_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('added', 'Added'), ('failed', 'Failed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('skip', 'Skip'), ('approval', 'Approval'), ('note', 'Note')], max_length=32),
        ),
    ]
