# Generated by Django 4.2.27 on 2025-12-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify_app", "0003_add_group_playlist_and_vote_session"),
        ("spotify_app", "0003_alter_playlistentry_status_alter_vote_vote_type"),
    ]

    operations = []
