# Generated by Django 4.2.27 on 2025-12-21 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='identifier',
            new_name='bot_message_identif_83c809_idx',
            old_name='bot_messages_identifier_identifier_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='bot_message_chat_id_7daaf8_idx',
            old_name='bot_messages_message_chat_id_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='bot_message_receive_49f421_idx',
            old_name='bot_messages_message_received_at_idx',
        ),
        migrations.AlterField(
            model_name='identifier',
            name='type',
            field=models.CharField(choices=[('phone', 'phone'), ('lid', 'lid'), ('group', 'group'), ('other', 'other')], default='phone', max_length=32),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
